 const PartDetials=
{
  "msg": "OK",
  "data": [
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "isVPMVisible": "FALSE",
      "Change Controlled": "True",
      "Service Make Buy Code": "Unassigned",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Target Cost": "0.0",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZNewPart",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZVarsh",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "False",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZYardly",
      "Originator": "TestProductEngineer",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
<<<<<<< HEAD
=======
      "Change Controlled": "False",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Purchase",
      "Spare Part": "Yes",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "230.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "500.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDemo",
      "Originator": "TestPrd01",
      "Estimated Cost": "230.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDemo001",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "400.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "3000.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscFrontBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "350.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "350.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "3.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscRearBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "300.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
>>>>>>> db9870845055042f5830f2a90062cc2a6e69230a
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "250.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "2.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZFrontBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "200.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
<<<<<<< HEAD
=======
      "V_Name": "IZNewPart",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
>>>>>>> db9870845055042f5830f2a90062cc2a6e69230a
      "V_Name": "IZPriya",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "300.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "3000.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZRearBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "250.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZSamplePart",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "350.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "3.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscRearBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "300.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "False",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZBrake",
      "Originator": "TestProductEngineer",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDemo001",
      "Originator": "TestPrd01",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "False",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "0.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "0.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZWebapp",
      "Originator": "TestProductEngineer",
      "Estimated Cost": "0.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Production",
      "Change Controlled": "True",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Design",
      "Spare Part": "No",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "400.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "3000.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDiscFrontBrake",
      "Originator": "TestPrd01",
      "Estimated Cost": "350.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    },
    {
      "Is Version": "FALSE",
      "Lead Time": "Unassigned",
      "Release Phase": "Development",
      "Change Controlled": "False",
      "isVPMVisible": "FALSE",
      "Design Purchase": "Purchase",
      "Spare Part": "Yes",
      "Service Make Buy Code": "Unassigned",
      "UOM Type": "Proportion",
      "End Item Override Enabled": "Yes",
      "Target Cost": "230.0",
      "Effectivity Date": null,
      "Lead Time Duration": "0.0",
      "Current Version": "0",
      "Weight": "500.0",
      "Unit of Measure": "EA (each)",
      "End Item": "No",
      "Part Classification": "Unassigned",
      "V_Name": "IZDemo",
      "Originator": "TestPrd01",
      "Estimated Cost": "230.0",
      "Production Make Buy Code": "Unassigned",
      "Material Category": "Metal"
    }
  ]
}
